swagger: '2.0'
tags:
  - name: Text Input
get:
  description: Input data yang akan diberi sentimen
responses:
    '200':
      description: Successful response
    '400':
      description: Bad Request
    '500':
      description: Internal Server Error
parameters:
  - name: body
    in: body
    schema:
      id : text_remove
      required:
        - text
      properties:
        text:
          type: string
          description: input your text